### ISSUE TITLE
can't find path in data.arc

### ISSUE THREAD

**Issue by PeterHo8888** [ultimate-research/UltimateModManager#12]
For any mod I try to install (through yuzu), UMM reports that it can't find the path (in the data.arc file, I assume).  I am on Smash v8.0.0 using the beta build of UMM.

Example:
![image](https://user-images.githubusercontent.com/20956390/87841977-1b208180-c877-11ea-8f85-d25e08e22af1.png)

and here is the relevant directory structure:
![image](https://user-images.githubusercontent.com/20956390/87842087-c6c9d180-c877-11ea-88d7-73334578ddb5.png)

I'm getting the full path straight out of the export from CrossArc, which is /root/fighter/common/param/fighter_param_motion.prc

UMM is seeing the data.arc file, and I know it is not corrupt.  If it means anything, it looks like the call to ArcReader::GetFileInformation() [here](https://github.com/ultimate-research/UltimateModManager/blob/42fcff57aeb285cc7a08d8d14b33b3e6beda9a30/source/mod_installer.h#L399) is not finding (and therefore not setting) the offset for the file in data.arc.  

Am I doing something fundamentally wrong?  I was following this [tutorial](https://gamebanana.com/tuts/13154) on gamebanana, and it appears one other person is having the same problem.

**Comment by Genwald** [comment]
The only thing I can think to be causing this is the state of the data.arc. I do not think this is an issue with UMM. I've just installed this file in yuzu myself to confirm that this isn't some edge case issue with this specific file when using yuzu and it installed fine for me. 
The path seems correct, so the only place that I can see this issue being introduced is in parsing the data.arc. 
I suppose it could also be an unexpected character in the path that isn't easily visible, but I don't think that's likely.

**Comment by PeterHo8888** [comment]
No files install for me, both on Windows and on Linux.  I'm wondering now if I dumped the wrong data.arc version (perhaps 1.0.0?), but there was no warning or error stating it.  Is there a simple way to verify my dump version?

**Comment by Genwald** [comment]
You can generate an md5 hash of the data.arc and compare to the list [here](https://gist.github.com/ThatNintendoNerd/2eff671ecbafd2043e9e48758a6e61bd). This will also verify that the dump is the same as everyone else's, with no corruption. Additionally, I believe crossarc tells you the version when you open the data.arc.

**Comment by PeterHo8888** [comment]
Apparently I had a v1.0.0 data.arc, even though I thought I dumped it correctly from yuzu.  Thanks for the help.  Closing.

**Comment by LucaBGt** [comment]
Just a quick question, is it bad to dump the v.1.0.0 data?
I have this exact same problem, including checking the hash and verifying that the dump is indeed v1.0.0, but my game is as well. Why could I be having this error?
Thanks for the help!

**Comment by Genwald** [comment]
1.0.0 is not supported by UMM at all. I recommend updating to the latest version of smash.
