### ISSUE TITLE
Wont open on Yuzu

### ISSUE THREAD

**Issue by PleaseIneedhelp** [ultimate-research/UltimateModManager#15]
Whenever I load the nro it gets stuck on the loading screen. On one of my several attempts I got "error while loading rom 0007-0023" if that helps with anything. Is there any idea why it wouldn't specifically load for me? I turned multicore off and have the controller in docked

**Comment by Genwald** [comment]
I'm not sure why this would happen, but you aren't the first to experience it. At the same time, this never happens on console, so I can't imagine that this is the fault of UMM, so I'll close this issue. If there is evidence that UMM causes this somehow let me know and I'll re-open.
