### ISSUE TITLE
UMM can't launch smash

### ISSUE THREAD

**Issue by kreepdaboom** [ultimate-research/UltimateModManager#22]
i've pressed X to launch smash, but nothing happens. The other buttons work just fine, but i cant override smash without launching it.

**Comment by Genwald** [comment]
This functionality works as expected for me. You can also launch smash by selecting it on the home screen like any other game. If this is a emulator you are using, that feature is not really expected to work, UMM was designed primarily to be used on console. I believe there are guides explaining what does or does not work on emulator.

**Comment by Genwald** [comment]
If this is happening on console, please re-open the issue.
