### ISSUE TITLE
Files are reported missing even though they aren't

### ISSUE THREAD

**Issue by Anonymous941** [ultimate-research/UltimateModManager#23]
I am using Yuzu Early Access 2926 and have created a playlist using [Sma5hMusic](https://github.com/Deinonychus71/Sma5hMusic) that built successfully.  I have copied it to `\sdmc\UltimateModManager\mods`.  When I try to install it and it gets to `writing file table (this might take a minute), I get a bunch of errors in red text:

```
"stream;/sound/bgm/bgm_whatever.n3sbank" does not exist, check its path
"stream;/sound/bgm/bgm_whatever.n3saudio" does not exist, check its path
```

These lines are repeated for every file I added.  When I check, the files _do_ exist in `\sdmc\UltimateModManager\mods\mod_name\stream;\sound\bgm`, but somehow it isn't detected by UltimateModManager.

**Comment by Genwald** [comment]
UMM is a tool for replacing files in the data.arc. Its saying they don't exist in the data.arc. It wouldn't be able to print out the name of your files if it didn't know they exist on SD.

**Comment by Genwald** [comment]
And Sma5hMusic is for automating the process of adding new music. UMM only replaces. So not really a compatible tool afaik.
