### ISSUE TITLE
Mods being deleted

### ISSUE THREAD

**Issue by RentaroArts** [ultimate-research/UltimateModManager#9]
Hi, I have followed may tutorials, but I have a problem loading mods. I will put the mods on my switch in the mods folder of UMM and when I try to install them on my switch, they don't show up at all. When I take out my SD card, the files are just gone. IDK if anyone can help, but if you can please.

**Comment by Genwald** [comment]
This sounds like an issue with the SD itself or the way in which you transfer files to it. UMM will not automatically delete your mod files. A decent way to test if this actually relates to UMM would be to repeat this exact process except, never open UMM after transferring the files, if the files still go missing, there is no way UMM could have been involved.

**Comment by RentaroArts** [comment]
Thanks, I will try with a different SD.
